<a href="https://colab.research.google.com/github/archachra/UCS420/blob/main/1024170073_Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr+2)
print(arr*3)
print(arr/2)


[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Q2

In [ ]:
#a)
arr=np.array([1, 2, 3, 6, 4, 5])
arr[::-1]
#b(i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
values,counts = np.unique(x,return_counts=True)
most_frequent = values[np.argmax(counts)]

print("Most frequent value in x:",most_frequent)
print("Indices:",np.where(x == most_frequent)[0])

#b(ii)

y = np.array([1,1,1,2,3,4,2,4,3,3])
values,counts = np.unique(y,return_counts=True)
most_frequent = values[np.argmax(counts)]

print("Most frequent value in y:",most_frequent)
print("Indices:",np.where(y == most_frequent)[0])


Most frequent value in x: 1
Indices: [0 5 7 8 9]
Most frequent value in y: 1
Indices: [0 1 2]


Q3

In [ ]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print(arr[0,1])
print(arr[2,0])

20
70


Q4

In [ ]:
Arnav = np.linspace(10,100,25)
print(Arnav)
print("Dimensions:",Arnav.ndim)
print("Shape:",Arnav.shape)
print("Total elements:",Arnav.size)
print("Data type:",Arnav.dtype)
print("Total bytes:",Arnav.nbytes)

print("Transpose using reshape:")
print(Arnav.reshape(5,5).T)

print("Transpose using T:")
print(Arnav.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape:
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5

In [ ]:
ucs420_arnav = np.array([[10,20,30,40],
                         [50,60,70,80],
                         [90,15,20,35]])

print("Mean:",np.mean(ucs420_arnav))
print("Median:",np.median(ucs420_arnav))
print("Maximum:",np.max(ucs420_arnav))
print("Minimum:",np.min(ucs420_arnav))
print("Unique:",np.unique(ucs420_arnav))

reshaped_ucs420_arnav = ucs420_arnav.reshape(4,3)
print("Reshaped array:")
print(reshaped_ucs420_arnav)

resized_ucs420_arnav = np.resize(ucs420_arnav,(2,3))
print("Resized array:")
print(resized_ucs420_arnav)

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
